### ISSUE TITLE
There must have been an error! Do you somehow a webserver running on your computer? Turn it off!

### ISSUE THREAD

**Issue by xxxoverkill** [neuro-sys/tumblr-downloader-client#24]
![image](https://cloud.githubusercontent.com/assets/17185854/26028497/6f4dd2cc-37e7-11e7-8a79-604d2c9287c0.png)

**Comment by neuro-sys** [comment]
@xxxoverkill That means there is an application running on your computer which is using port 80. You need to find out what that is, and stop it, so that port 80 is free.

I was too lazy to find a workaround with oauth redirection, that's why port 80 needs to be available for this to work.

I'll think something for this, thanks for reporting.
