### ISSUE TITLE
Finished without doing any downloads

### ISSUE THREAD

**Issue by sandhawke** [neuro-sys/tumblr-downloader-client#28]
I think I did the oauth setup correctly.  When I click "Download" the status log just says:

> * Starting...
> Initializing environment...
> done
> Authorizing on tumblr...
> * Finished...

It made a subdirectory under that target location, but that's it.

I don't really understand oauth, but I'm confused how localhost could work, esp behind NAT.  Do I need to run this on a machine with non-NAT access and replace localhost with the real hostname?

**Comment by sandhawke** [comment]
Tempted to install from source and try some debugging, but scared of qt....

**Comment by neuro-sys** [comment]
@sandhawke Hey, thanks for trying this out. Setting localhost is only required because OAuth works such that Tumblr requires some (any) host to redirect the user to with the oauth token passed on URL. And for security reasons, it requires you to define the URL on tumblr's website. In our case, I don't care where it's redirected to, so it happens to be localhost:80, and I grab the token from the URL (without caring if it point to a valid host). So being behind a firewall or router is not a problem.

However, I'd like to know which version of the application you are using, and the operating system. And also I will increase the amount of logs to make troubleshooting easier.

**Comment by sandhawke** [comment]
V1.4 (Linux) on Ubuntu 17.04

**Comment by sandhawke** [comment]
(I'll double check port 80 when I get home, but pretty sure there wasn't.  Mobile right now)

**Comment by sandhawke** [comment]
I tried it on a fresh digitalocean Ubuntu 16.04.2 LTS machine and saw exactly the same behavior.

I connected via ssh -X so that it could open the window on my display.

Then:
```sh
$ curl -L -o tdc https://github.com/neuro-sys/tumblr-downloader-client/releases/download/v1.4/Tumblr_Downloader_GUI-git.0919a76-x86_64.AppImage
$ chmod 755 tdc
$ ./tdc
```

**Comment by sandhawke** [comment]
I also tried v1.1 and v1.3.

v1.3 was like v1.4.   One other thing I noticed is that none of the values for User Name, Password, Consumer Key, or Consumer Secret affect anything.  Behavior is the same with them blank.

With 1.1, they matter.   With them wrong, I get `Form not found matching expr 'form'.`.  With them right, it says 'Starting...' then sits there with the CPU pegged, no other output, no files created.  I gave it five minutes before clicking 'Cancel' and it stopped.

**Comment by Naz-z** [comment]
I am having the same issue, MacOS 10.12.5. I have no programs listening on port 80. Tumblr_Downloader_GUI-git.0919a76-x86_64

* Starting...
Initializing environment...
done
Authorizing on tumblr...
success
Ask for liked posts 1 - 20...
* Finished...

**Comment by RolandTi** [comment]
Solved that problem by removing "http://" from tumblr url.

**Comment by vh133** [comment]
i have the same problem. the downloader worked error-free until about 2 months ago. since then it doesn't work anymore... Just Authorizing on tumblr..., Finished... 
this behavior started simultaneously on an Mac and on a linux computer. could it be that tumblr changed something?
Maybe someone can help with this problem.

Thanks

**Comment by neuro-sys** [comment]
@vh133 New version here: https://github.com/neuro-sys/tumblr-downloader-client/releases/tag/0.0.1
